CATEGORY_KEYWORDS = {
    "business": [
        "trump",
        "stock",
        "market",
        "finance",
        "business",
        "company",
        "earnings",
        "ipo",
        "merger",
        "acquisition",
        "trade",
        "economy",
        "economic",
        "invest",
        "bank",
        "revenue",
    ],
    "entertainment": [
        "movie",
        "music",
        "celebrity",
        "tv",
        "show",
        "film",
        "concert",
        "theater",
        "festival",
        "actor",
        "actress",
        "award",
        "entertainment",
        "hollywood",
        "bollywood",
    ],
    "health": [
        "health",
        "medicine",
        "doctor",
        "hospital",
        "covid",
        "vaccine",
        "disease",
        "virus",
        "medical",
        "wellness",
        "fitness",
        "nutrition",
        "mental health",
        "surgery",
    ],
    "science": [
        "science",
        "research",
        "study",
        "space",
        "nasa",
        "discovery",
        "experiment",
        "scientist",
        "physics",
        "chemistry",
        "biology",
        "astronomy",
        "laboratory",
    ],
    "sports": [
        "sport",
        "game",
        "match",
        "tournament",
        "player",
        "score",
        "goal",
        "win",
        "team",
        "league",
        "olympic",
        "athlete",
        "coach",
        "cricket",
        "football",
        "soccer",
        "nba",
        "nfl",
        "tennis",
        "golf",
    ],
    "technology": [
        "tech",
        "technology",
        "software",
        "hardware",
        "ai",
        "gadget",
        "app",
        "robot",
        "computer",
        "internet",
        "smartphone",
        "device",
        "startup",
        "innovation",
        "digital",
        "cyber",
        "cloud",
        "data",
    ],
}


def map_article_to_category(article):
    text = f"{article.get('title', '')} {article.get('description', '')} {article.get('content', '')}".lower()
    for category, keywords in CATEGORY_KEYWORDS.items():
        if any(keyword in text for keyword in keywords):
            return category
    return "general"
